PPWuLiu/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', RedirectView.as_view(url='tms/login')),
    path('tms/', include('wuliu.urls')),
    path('utils/', include('utils.urls')),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

utils/urls.py
from django.urls import path

from . import views

app_name = "utils"
urlpatterns = [
    path("export_excel", views.export_excel, name="export_excel"),
]

wuliu/urls.py
from django.urls import path, include


# Unused
from wuliu import views, apis


def easy_path(view_func):
    """ 只需给定视图函数, route和name都设置为视图函数的名字 """
    return path(view_func.__name__, view_func, name=view_func.__name__)

app_name = "wuliu"
# urlpatterns = []

urlpatterns = [
    # 登录
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("change_password", views.change_password, name="change_password"),
    path("", views.welcome, name="welcome"),
    path("welcome_action.js", views.welcome_js, name="welcome_js"),
    # 系统设置
    path("settings/", include([
        path("manage_users", views.manage_users, name="manage_users"),
        path("add_user", views.add_user, name="add_user"),
        path("manage_user_permission", views.manage_user_permission, name="manage_user_permission"),
        path("batch_edit_user_permission", views.batch_edit_user_permission, name="batch_edit_user_permission"),
    ])),
    # 运单管理
    path("waybill/", include([
        path("add", views.add_waybill, name="add_waybill"),
        path("edit", views.edit_waybill, name="edit_waybill"),
        path("edit.js", views.edit_waybill_js, name="edit_waybill_js"),
        path("manage", views.ManageWaybill.as_view(), name="manage_waybill"),
        path("manage.js", views.manage_waybill_js, name="manage_waybill_js"),
        path("detail/<int:waybill_id>", views.detail_waybill, name="detail_waybill"),
        path("quick_search", views.quick_search_waybill, name="quick_search_waybill"),
        path("confirm_return", views.confirm_return_waybill, name="confirm_return_waybill"),
    ])),
    # 发车管理
    path("transport_out/", include([
        path("add", views.add_transport_out, name="add_transport_out"),
        path("edit", views.edit_transport_out, name="edit_transport_out"),
        path("edit.js", views.edit_transport_out_js, name="edit_transport_out_js"),
        path("manage", views.manage_transport_out, name="manage_transport_out"),
        path("manage.js", views.manage_transport_out_js, name="manage_transport_out_js"),
        path("detail", views.detail_transport_out, name="detail_transport_out"),
        path("search_waybills", views.SearchWaybillsToTransportOut.as_view(), name="search_waybills_to_transport_out"),
        path("add_waybills", views.add_waybills_to_transport_out, name="add_waybills_to_transport_out"),
    ])),
    # 到货管理
    path("arrival/", include([
        path("manage", views.manage_arrival, name="manage_arrival"),
        path("confirm", views.confirm_arrival, name="confirm_arrival"),
    ])),
    # 客户签收
    path("sign_for/", include([
        path("manage", views.ManageSignFor.as_view(), name="manage_sign_for"),
        path("confirm", views.confirm_sign_for, name="confirm_sign_for"),
        path("confirm.js", views.confirm_sign_for_js, name="confirm_sign_for_js"),
    ])),
    # 财务管理
    path("finance/", include([
        path("department_payment/", include([
            path("add", views.add_department_payment, name="add_department_payment"),
            path("manage", views.manage_department_payment, name="manage_department_payment"),
            path("manage.js", views.manage_department_payment_js, name="manage_department_payment_js"),
            path("detail/<int:dp_id>", views.detail_department_payment, name="detail_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("add", views.add_cargo_price_payment, name="add_cargo_price_payment"),
            path("edit", views.edit_cargo_price_payment, name="edit_cargo_price_payment"),
            path("edit.js", views.edit_cargo_price_payment_js, name="edit_cargo_price_payment_js"),
            path("detail/<int:cpp_id>", views.detail_cargo_price_payment, name="detail_cargo_price_payment"),
            path("manage", views.manage_cargo_price_payment, name="manage_cargo_price_payment"),
            path("manage.js", views.manage_cargo_price_payment_js, name="manage_cargo_price_payment_js"),
        ])),
        path("customer_score_log/", include([
            path("manage", views.manage_customer_score, name="manage_customer_score"),
            path("add", views.add_customer_score_log, name="add_customer_score_log"),
        ])),
    ])),
    # 业务报表
    path("report_table/", include([
        path("src_waybill", views.ReportTableSrcWaybill.as_view(), name="report_table_src_waybill"),
        path("stock_waybill", views.ReportTableStockWaybill.as_view(), name="report_table_stock_waybill"),
        path("dst_waybill", views.ReportTableDstWaybill.as_view(), name="report_table_dst_waybill"),
        path("dst_stock_waybill", views.ReportTableDstStockWaybill.as_view(), name="report_table_dst_stock_waybill"),
        path("sign_for_waybill", views.ReportTableSignForWaybill.as_view(), name="report_table_sign_for_waybill"),
    ])),
    # apis
    path("api/", include([
        path("gen_standard_fee", apis.gen_standard_fee, name="api_gen_standard_fee"),
        path("check_old_password", apis.check_old_password, name="api_check_old_password"),
        # 用以获取模型对象属性的api
        path("get/", include([
            path("customer_info", apis.get_customer_info, name="api_get_customer_info"),
            path("department_info", apis.get_department_info, name="api_get_department_info"),
            path("waybills_info", apis.get_waybills_info, name="api_get_waybills_info"),
            path("truck_info", apis.get_truck_info, name="api_get_truck_info"),
            path("user_info", apis.get_user_info, name="api_get_user_info"),
            path("user_permission", apis.get_user_permission, name="api_get_user_permission"),
        ])),
        # 用以操作模型和会话的api
        path("remove_waybill_when_add_transport_out", apis.remove_waybill_when_add_transport_out,
             name="api_remove_waybill_when_add_transport_out"),
        path("remove_waybill_when_edit_transport_out", apis.remove_waybill_when_edit_transport_out,
             name="api_remove_waybill_when_edit_transport_out"),
        path("add_waybill_when_confirm_sign_for", apis.add_waybill_when_confirm_sign_for,
             name="api_add_waybill_when_confirm_sign_for"),
        path("add_waybill_when_edit_cargo_price_payment", apis.add_waybill_when_edit_cargo_price_payment,
             name="api_add_waybill_when_edit_cargo_price_payment"),
        path("drop_waybill", apis.DropWaybill.as_view(), name="api_drop_waybill"),
        path("drop_transport_out", apis.DropTransportOut.as_view(), name="api_drop_transport_out"),
        path("start_transport_out", apis.StartTransportOut.as_view(), name="api_start_transport_out"),
        path("confirm_arrival", apis.ConfirmArrival.as_view(), name="api_confirm_arrival"),
        path("confirm_sign_for", apis.ConfirmSignFor.as_view(), name="api_confirm_sign_for"),
        path("department_payment/", include([
            path("modify_remark", apis.ModifyRemarkDepartmentPayment.as_view(),
                 name="api_modify_remark_department_payment"),
            path("drop", apis.DropDepartmentPayment.as_view(),
                 name="api_drop_department_payment"),
            path("review", apis.ConfirmReviewDepartmentPayment.as_view(),
                 name="api_review_department_payment"),
            path("pay", apis.ConfirmPayDepartmentPayment.as_view(),
                 name="api_pay_department_payment"),
            path("settle_accounts", apis.ConfirmSettleAccountsDepartmentPayment.as_view(),
                 name="api_settle_accounts_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("drop", apis.DropCargoPricePayment.as_view(),
                 name="api_drop_cargo_price_payment"),
            path("submit", apis.ConfirmSubmitCargoPricePayment.as_view(),
                 name="api_submit_cargo_price_payment"),
            path("review", apis.ConfirmReviewCargoPricePayment.as_view(),
                 name="api_review_cargo_price_payment"),
            path("reject", apis.ConfirmRejectCargoPricePayment.as_view(),
                 name="api_reject_cargo_price_payment"),
            path("pay", apis.ConfirmPayCargoPricePayment.as_view(),
                 name="api_pay_cargo_price_payment"),
        ])),
    ])),
]

wuliu/templates/wuliu/_js/manage_cargo_price_payment.js.html
{% load wuliu_extras %}
// <script>
$(document).ready(function() {
  document.querySelector('[name="create_date_end"]')._duDatepicker.minDate = $('#form-search_cargo_price_payment [name="create_date_start"]').val();
  $('#form-search_cargo_price_payment [name="create_date_end"]').on("datechanged", function() {
    document.querySelector('[name="create_date_start"]')._duDatepicker.maxDate = $(this).val();
  });
  $('#form-search_cargo_price_payment [name="create_date_start"]').on("datechanged", function() {
    document.querySelector('[name="create_date_end"]')._duDatepicker.minDate = $(this).val();
  });
  function get_checked_cpp_only_one() {
    let checked_cpp = find_datatable_rows_clicked(cargo_price_payment_table);
    if (checked_cpp.length !== 1) {
      mdtoast_error("请选择一个转账单。");
      return;
    }
    return checked_cpp[0];
  }
  const logged_user_id = "{{ request.session.user.id }}";
{% if "manage_cargo_price_payment__add_edit_delete_submit"|is_logged_user_has_perm:request %}
  $("#button_cpp_edit").click(function() {
    let checked_cpp = get_checked_cpp_only_one();
    if (! checked_cpp) return;
    let checked_cpp_status = checked_cpp.find("[data-status_id]").attr("data-status_id");
    if (checked_cpp_status != "{{ CPP_STATUSES.Created }}" && checked_cpp_status != "{{ CPP_STATUSES.Rejected }}") {
      mdtoast_error("提交后的转账单不允许修改。");
      return;
    }
    if (logged_user_id != checked_cpp.find("[data-user_id]").attr("data-user_id")) {
      mdtoast_error("你没有修改该转账单的权限。");
      return;
    }
    let checked_cpp_id = checked_cpp.find("[data-cpp_id]").attr("data-cpp_id");
    window.location.replace("{% url 'wuliu:edit_cargo_price_payment' %}?cpp_id=" + checked_cpp_id);
  });
  $("#button_cpp_delete").click(function() {
    let checked_cpp = get_checked_cpp_only_one();
    if (! checked_cpp) return;
    let checked_cpp_status = checked_cpp.find("[data-status_id]").attr("data-status_id");
    if (checked_cpp_status != "{{ CPP_STATUSES.Created }}" && checked_cpp_status != "{{ CPP_STATUSES.Rejected }}") {
      mdtoast_error("提交后的转账单不允许删除。");
      return;
    }
    if (logged_user_id != checked_cpp.find("[data-user_id]").attr("data-user_id")) {
      mdtoast_error("你没有删除该转账单的权限。");
      return;
    }
    confirm_dialog(
      "确认删除", "你确定要删除该转账单吗？",
      {
        okClick: function() {
          this.hide();
          $.post(
            "{% url 'wuliu:api_drop_cargo_price_payment' %}",
            {
              "cpp_id": checked_cpp.find("[data-cpp_id]").attr("data-cpp_id"),
            },
            function(data, status) {
              if (data.code === 200) {
                cargo_price_payment_table.row(checked_cpp).remove().draw();
                mdtoast_success("删除成功。");
              } else {
                alert_dialog("删除失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
  $("#button_cpp_confirm_submit").click(function() {
    let checked_cpp = get_checked_cpp_only_one();
    if (! checked_cpp) return;
    let checked_cpp_status = checked_cpp.find("[data-status_id]").attr("data-status_id");
    if (checked_cpp_status != "{{ CPP_STATUSES.Created }}" && checked_cpp_status != "{{ CPP_STATUSES.Rejected }}") {
      mdtoast_error("提交后的转账单不允许重复提交。");
      return;
    }
    if (logged_user_id != checked_cpp.find("[data-user_id]").attr("data-user_id")) {
      mdtoast_error("你没有提交该转账单的权限。");
      return;
    }
    confirm_dialog(
      "确认提交", "你确定要提交该转账单吗？",
      {
        okClick: function() {
          this.hide();
          $.post(
            "{% url 'wuliu:api_submit_cargo_price_payment' %}",
            {
              "cpp_id": checked_cpp.find("[data-cpp_id]").attr("data-cpp_id"),
            },
            function(data, status) {
              if (data.code === 200) {
                checked_cpp.find("[data-status_id]").attr("data-status_id", "{{ CPP_STATUSES.Submitted }}").html("{{ CPP_STATUSES.Submitted.label }}");
                mdtoast_success("提交成功。");
              } else {
                alert_dialog("提交失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% endif %}
{% if "manage_cargo_price_payment__review_reject"|is_logged_user_has_perm:request %}
  $("#button_cpp_confirm_review").click(function() {
    let checked_cpp = get_checked_cpp_only_one();
    if (! checked_cpp) return;
    if (checked_cpp.find("[data-status_id]").attr("data-status_id") != "{{ CPP_STATUSES.Submitted }}") {
      mdtoast_error('只能审核"已提交"状态的转账单。');
      return;
    }
    confirm_dialog(
      "确认审核", "你确定要审核该转账单吗？此操作无法撤销！",
      {
        okClick: function() {
          this.hide();
          $.post(
            "{% url 'wuliu:api_review_cargo_price_payment' %}",
            {
              "cpp_id": checked_cpp.find("[data-cpp_id]").attr("data-cpp_id"),
            },
            function(data, status) {
              if (data.code === 200) {
                checked_cpp.find("[data-status_id]").attr("data-status_id", "{{ CPP_STATUSES.Reviewed }}").html("{{ CPP_STATUSES.Reviewed.label }}");
                mdtoast_success("操作成功。");
              } else {
                alert_dialog("操作失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
  $("#button_cpp_confirm_reject").click(function() {
    let checked_cpp = get_checked_cpp_only_one();
    if (! checked_cpp) return;
    if (checked_cpp.find("[data-status_id]").attr("data-status_id") != "{{ CPP_STATUSES.Submitted }}") {
      mdtoast_error('只能驳回"已提交"状态的转账单。');
      return;
    }
    confirm_dialog(
      "确认驳回",
      '请输入驳回理由：' +
      '<form class="form">' +
        '<textarea ' +
          'type="text" name="__reject_reason" ' +
          'class="form-control" style="resize: vertical; height: 60px;">' +
        '</textarea>' +
      '</form>',
      {
        okClick: function() {
          let reject_reason_text = $('[name="__reject_reason"]').val().trim();
          if (! reject_reason_text) return;
          this.hide();
          $.post(
            "{% url 'wuliu:api_reject_cargo_price_payment' %}",
            {
              "cpp_id": checked_cpp.find("[data-cpp_id]").attr("data-cpp_id"),
              "reject_reason": reject_reason_text,
            },
            function(data, status) {
              if (data.code === 200) {
                checked_cpp.find("[data-status_id]").attr("data-status_id", "{{ CPP_STATUSES.Rejected }}").html("{{ CPP_STATUSES.Rejected.label }}");
                mdtoast_success("操作成功。");
              } else {
                alert_dialog("操作失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% endif %}
{% if "manage_cargo_price_payment__pay"|is_logged_user_has_perm:request %}
  $("#button_cpp_confirm_pay").click(function() {
    let checked_cpp = get_checked_cpp_only_one();
    if (! checked_cpp) return;
    if (checked_cpp.find("[data-status_id]").attr("data-status_id") != "{{ CPP_STATUSES.Reviewed }}") {
      mdtoast_error('只能支付"已审核"状态的转账单。');
      return;
    }
    confirm_dialog(
      "确认支付",
      "<p>请确保已成功完成支付，且收款人确实收到转账之后再进行确认。</p>" +
      "<p>一旦确认，转账将统计入财务系统，此操作无法撤销！</p>",
      {
        okClick: function() {
          this.hide();
          $.post(
            "{% url 'wuliu:api_pay_cargo_price_payment' %}",
            {
              "cpp_id": checked_cpp.find("[data-cpp_id]").attr("data-cpp_id"),
            },
            function(data, status) {
              if (data.code === 200) {
                checked_cpp.find("[data-status_id]").attr("data-status_id", "{{ CPP_STATUSES.Paid }}").html("{{ CPP_STATUSES.Paid.label }}");
                checked_cpp.find("[data-key='cpp_settle_accounts_time']").attr("data-order", data.data.cpp_settle_accounts_time_timestamp).html(data.data.cpp_settle_accounts_time);
                mdtoast_success("操作成功。");
              } else {
                alert_dialog("操作失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% endif %}
});
// </script>

wuliu/templates/wuliu/_js/manage_department_payment.js.html
{% load wuliu_extras %}
// <script>
$(document).ready(function() {
  document.querySelector('[name="payment_date_end"]')._duDatepicker.minDate = $('#form-search_department_payment [name="payment_date_start"]').val();
  $('#form-search_department_payment [name="payment_date_end"]').on("datechanged", function() {
    document.querySelector('[name="payment_date_start"]')._duDatepicker.maxDate = $(this).val();
  });
  $('#form-search_department_payment [name="payment_date_start"]').on("datechanged", function() {
    document.querySelector('[name="payment_date_end"]')._duDatepicker.minDate = $(this).val();
  });
  const user_dept_id = "{{ request.session.user.department_id }}";
  function get_checked_dp_all() {
    let checked_dp = find_datatable_rows_clicked(dp_search_result_table);
    if (checked_dp.length === 0) {
      mdtoast_error("请至少选择一个回款单。");
      return;
    }
    return checked_dp;
  }
  function get_checked_dp_only_one() {
    let checked_dp = find_datatable_rows_clicked(dp_search_result_table);
    if (checked_dp.length !== 1) {
      mdtoast_error("请选择一个回款单。");
      return;
    }
    return checked_dp[0];
  }
  $("#button_dp_edit_remark").click(function() {
    let checked_dp = get_checked_dp_only_one();
    if (! checked_dp) return;
    if (checked_dp.find("[data-status_id]").attr("data-status_id") == "{{ DP_STATUSES.Settled.value }}") {
      mdtoast_error("已结算的回款单不允许修改备注。");
      return;
    }
    let remark_type;
    if (user_dept_id == checked_dp.find("[data-src_dept_id]").attr("data-src_dept_id")) {
      remark_type = "src";
    } else if (user_dept_id == checked_dp.find("[data-dst_dept_id]").attr("data-dst_dept_id")) {
      remark_type = "dst";
    } else {
      mdtoast_error("你没有修改备注的权限。");
      return;
    }
    confirm_dialog(
      "修改" + (remark_type === "src" ? "回款部门" : "收款部门") + "备注",
      '请输入：' +
      '<form class="form mt-2">' +
        '<textarea ' +
          'type="text" name="__remark" ' +
          'class="form-control" style="resize: vertical; height: 60px;">' +
          checked_dp.find('[data-key="dp_'+remark_type+'_remark"]').text() +
        '</textarea>' +
      '</form>',
      {
        okClick: function() {
          let remark_text = $('[name="__remark"]').val().trim();
          if (! remark_text) return;
          this.hide();
          $.post(
            "{% url 'wuliu:api_modify_remark_department_payment' %}",
            {
              "dp_id": checked_dp.find("[data-dp_id]").attr("data-dp_id"),
              "remark_dept_type": remark_type,
              "remark_text": remark_text,
            },
            function(data, status) {
              if (data.code === 200) {
                checked_dp.find('[data-key="dp_'+remark_type+'_remark"]').html(remark_text);
                mdtoast_success("备注修改成功。");
              } else {
                alert_dialog("备注修改失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% if "manage_department_payment__pay"|is_logged_user_has_perm:request %}
  $("#button_dp_confirm_pay").click(function() {
    let checked_dp = get_checked_dp_all();
    if (! checked_dp) return;
    for (let jq_obj of checked_dp.toArray()) {
      if (jq_obj.find("[data-status_id]").attr("data-status_id") != "{{ DP_STATUSES.Reviewed.value }}") {
        mdtoast_error('只能对"已审核"的回款单进行确认支付操作。');
        return;
      }
      if (jq_obj.find("[data-src_dept_id]").attr("data-src_dept_id") != user_dept_id) {
        mdtoast_error("只能对当前部门的回款单进行确认支付操作。");
        return;
      }
    }
    confirm_dialog(
      "确认支付",
      "请确保已成功完成支付，且收款部门确实收到转账之后再进行确认。",
      {
        okClick: function() {
          let checked_dp_ids = checked_dp.map(function(jq_obj) {
            return jq_obj.find("[data-dp_id]").attr("data-dp_id");
          });
          this.hide();
          $.post(
            "{% url 'wuliu:api_pay_department_payment' %}",
            {
              "dp_ids": checked_dp_ids.join(","),
            },
            function(data, status) {
              if (data.code === 200) {
                checked_dp.each(function(jq_obj) {
                  jq_obj.find("[data-status_id]").attr("data-status_id", "{{ DP_STATUSES.Paid }}").html("{{ DP_STATUSES.Paid.label }}");
                });
                mdtoast_success("提交成功。");
              } else {
                alert_dialog("提交失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% endif %}
{% if "manage_department_payment__add_delete"|is_logged_user_has_perm:request %}
  $("#button_dp_delete").click(function() {
    let checked_dp = get_checked_dp_all();
    if (! checked_dp) return;
    for (let jq_obj of checked_dp.toArray()) {
      if (jq_obj.find("[data-status_id]").attr("data-status_id") != "{{ DP_STATUSES.Created.value }}") {
        mdtoast_error("只能删除尚未审核的回款单。");
        return;
      }
    }
    confirm_dialog(
      "删除回款单",
      "你确定要删除这些回款单吗？",
      {
        okClick: function() {
          let checked_dp_ids = checked_dp.map(function(jq_obj) {
            return jq_obj.find("[data-dp_id]").attr("data-dp_id");
          });
          this.hide();
          $.post(
            "{% url 'wuliu:api_drop_department_payment' %}",
            {
              "dp_ids": checked_dp_ids.join(","),
            },
            function(data, status) {
              if (data.code === 200) {
                checked_dp.each(function(row) {
                  dp_search_result_table.row(row).remove();
                });
                dp_search_result_table.draw();
                mdtoast_success("删除成功。");
              } else {
                alert_dialog("删除失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% endif %}
{% if "manage_department_payment__review"|is_logged_user_has_perm:request %}
  $("#button_dp_confirm_review").click(function() {
    let checked_dp = get_checked_dp_all();
    if (! checked_dp) return;
    for (let jq_obj of checked_dp.toArray()) {
      if (jq_obj.find("[data-status_id]").attr("data-status_id") != "{{ DP_STATUSES.Created.value }}") {
        mdtoast_error("只能审核尚未审核的回款单。");
        return;
      }
    }
    confirm_dialog(
      "审核回款单",
      "你确定要审核这些回款单吗？此操作无法撤销！",
      {
        okClick: function() {
          let checked_dp_ids = checked_dp.map(function(jq_obj) {
            return jq_obj.find("[data-dp_id]").attr("data-dp_id");
          });
          this.hide();
          $.post(
            "{% url 'wuliu:api_review_department_payment' %}",
            {
              "dp_ids": checked_dp_ids.join(","),
            },
            function(data, status) {
              if (data.code === 200) {
                checked_dp.each(function(jq_obj) {
                  jq_obj.find("[data-status_id]").attr("data-status_id", "{{ DP_STATUSES.Reviewed }}").html("{{ DP_STATUSES.Reviewed.label }}");
                });
                mdtoast_success("审核成功。");
              } else {
                alert_dialog("审核失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% endif %}
{% if "manage_department_payment__settle"|is_logged_user_has_perm:request %}
  $("#button_dp_confirm_settle_accounts").click(function() {
    let checked_dp = get_checked_dp_all();
    if (! checked_dp) return;

    for (let jq_obj of checked_dp.toArray()) {
      if (jq_obj.find("[data-status_id]").attr("data-status_id") != "{{ DP_STATUSES.Paid.value }}") {
        mdtoast_error('只能结算"已支付"的回款单。');
        return;
      }
    }
    confirm_dialog(
      "确认结算",
      "<p>请确保确实收到转账之后再进行确认结算操作，</p>" +
      "<p>一旦确认，转账将统计入财务系统，</p>" +
      "<p>此操作无法撤销！</p>",
      {
        okClick: function() {
          let checked_dp_ids = checked_dp.map(function(jq_obj) {
            return jq_obj.find("[data-dp_id]").attr("data-dp_id");
          });
          this.hide();
          $.post(
            "{% url 'wuliu:api_settle_accounts_department_payment' %}",
            {
              "dp_ids": checked_dp_ids.join(","),
            },
            function(data, status) {
              if (data.code === 200) {
                checked_dp.each(function(jq_obj) {
                  jq_obj.find("[data-status_id]").attr("data-status_id", "{{ DP_STATUSES.Settled }}").html("{{ DP_STATUSES.Settled.label }}");
                  jq_obj.find('[data-key="dp_settle_accounts_time"]').attr("data-order", data.data.dp_settle_accounts_time_timestamp).html(data.data.dp_settle_accounts_time);
                });
                mdtoast_success("提交成功。");
              } else {
                alert_dialog("提交失败："+data.data.message);
              }
            }
          )
        }
      }
    );
  });
{% endif %}
});
// </script>