PPWuLiu/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', RedirectView.as_view(url='tms/login')),
    path('tms/', include('wuliu.urls')),
    path('utils/', include('utils.urls')),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

utils/urls.py
from django.urls import path

from . import views

app_name = "utils"
urlpatterns = [
    path("export_excel", views.export_excel, name="export_excel"),
]

wuliu/urls.py
from django.urls import path, include


# Unused
from wuliu import views, apis


def easy_path(view_func):
    """ 只需给定视图函数, route和name都设置为视图函数的名字 """
    return path(view_func.__name__, view_func, name=view_func.__name__)

app_name = "wuliu"
# urlpatterns = []

urlpatterns = [
    # 登录
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("change_password", views.change_password, name="change_password"),
    path("", views.welcome, name="welcome"),
    path("welcome_action.js", views.welcome_js, name="welcome_js"),
    # 系统设置
    path("settings/", include([
        path("manage_users", views.manage_users, name="manage_users"),
        path("add_user", views.add_user, name="add_user"),
        path("manage_user_permission", views.manage_user_permission, name="manage_user_permission"),
        path("batch_edit_user_permission", views.batch_edit_user_permission, name="batch_edit_user_permission"),
    ])),
    # 运单管理
    path("waybill/", include([
        path("add", views.add_waybill, name="add_waybill"),
        path("edit", views.edit_waybill, name="edit_waybill"),
        path("edit.js", views.edit_waybill_js, name="edit_waybill_js"),
        path("manage", views.ManageWaybill.as_view(), name="manage_waybill"),
        path("manage.js", views.manage_waybill_js, name="manage_waybill_js"),
        path("detail/<int:waybill_id>", views.detail_waybill, name="detail_waybill"),
        path("quick_search", views.quick_search_waybill, name="quick_search_waybill"),
        path("confirm_return", views.confirm_return_waybill, name="confirm_return_waybill"),
    ])),
    # 发车管理
    path("transport_out/", include([
        path("add", views.add_transport_out, name="add_transport_out"),
        path("edit", views.edit_transport_out, name="edit_transport_out"),
        path("edit.js", views.edit_transport_out_js, name="edit_transport_out_js"),
        path("manage", views.manage_transport_out, name="manage_transport_out"),
        path("manage.js", views.manage_transport_out_js, name="manage_transport_out_js"),
        path("detail", views.detail_transport_out, name="detail_transport_out"),
        path("search_waybills", views.SearchWaybillsToTransportOut.as_view(), name="search_waybills_to_transport_out"),
        path("add_waybills", views.add_waybills_to_transport_out, name="add_waybills_to_transport_out"),
    ])),
    # 到货管理
    path("arrival/", include([
        path("manage", views.manage_arrival, name="manage_arrival"),
        path("confirm", views.confirm_arrival, name="confirm_arrival"),
    ])),
    # 客户签收
    path("sign_for/", include([
        path("manage", views.ManageSignFor.as_view(), name="manage_sign_for"),
        path("confirm", views.confirm_sign_for, name="confirm_sign_for"),
        path("confirm.js", views.confirm_sign_for_js, name="confirm_sign_for_js"),
    ])),
    # 财务管理
    path("finance/", include([
        path("department_payment/", include([
            path("add", views.add_department_payment, name="add_department_payment"),
            path("manage", views.manage_department_payment, name="manage_department_payment"),
            path("manage.js", views.manage_department_payment_js, name="manage_department_payment_js"),
            path("detail/<int:dp_id>", views.detail_department_payment, name="detail_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("add", views.add_cargo_price_payment, name="add_cargo_price_payment"),
            path("edit", views.edit_cargo_price_payment, name="edit_cargo_price_payment"),
            path("edit.js", views.edit_cargo_price_payment_js, name="edit_cargo_price_payment_js"),
            path("detail/<int:cpp_id>", views.detail_cargo_price_payment, name="detail_cargo_price_payment"),
            path("manage", views.manage_cargo_price_payment, name="manage_cargo_price_payment"),
            path("manage.js", views.manage_cargo_price_payment_js, name="manage_cargo_price_payment_js"),
        ])),
        path("customer_score_log/", include([
            path("manage", views.manage_customer_score, name="manage_customer_score"),
            path("add", views.add_customer_score_log, name="add_customer_score_log"),
        ])),
    ])),
    # 业务报表
    path("report_table/", include([
        path("src_waybill", views.ReportTableSrcWaybill.as_view(), name="report_table_src_waybill"),
        path("stock_waybill", views.ReportTableStockWaybill.as_view(), name="report_table_stock_waybill"),
        path("dst_waybill", views.ReportTableDstWaybill.as_view(), name="report_table_dst_waybill"),
        path("dst_stock_waybill", views.ReportTableDstStockWaybill.as_view(), name="report_table_dst_stock_waybill"),
        path("sign_for_waybill", views.ReportTableSignForWaybill.as_view(), name="report_table_sign_for_waybill"),
    ])),
    # apis
    path("api/", include([
        path("gen_standard_fee", apis.gen_standard_fee, name="api_gen_standard_fee"),
        path("check_old_password", apis.check_old_password, name="api_check_old_password"),
        # 用以获取模型对象属性的api
        path("get/", include([
            path("customer_info", apis.get_customer_info, name="api_get_customer_info"),
            path("department_info", apis.get_department_info, name="api_get_department_info"),
            path("waybills_info", apis.get_waybills_info, name="api_get_waybills_info"),
            path("truck_info", apis.get_truck_info, name="api_get_truck_info"),
            path("user_info", apis.get_user_info, name="api_get_user_info"),
            path("user_permission", apis.get_user_permission, name="api_get_user_permission"),
        ])),
        # 用以操作模型和会话的api
        path("remove_waybill_when_add_transport_out", apis.remove_waybill_when_add_transport_out,
             name="api_remove_waybill_when_add_transport_out"),
        path("remove_waybill_when_edit_transport_out", apis.remove_waybill_when_edit_transport_out,
             name="api_remove_waybill_when_edit_transport_out"),
        path("add_waybill_when_confirm_sign_for", apis.add_waybill_when_confirm_sign_for,
             name="api_add_waybill_when_confirm_sign_for"),
        path("add_waybill_when_edit_cargo_price_payment", apis.add_waybill_when_edit_cargo_price_payment,
             name="api_add_waybill_when_edit_cargo_price_payment"),
        path("drop_waybill", apis.DropWaybill.as_view(), name="api_drop_waybill"),
        path("drop_transport_out", apis.DropTransportOut.as_view(), name="api_drop_transport_out"),
        path("start_transport_out", apis.StartTransportOut.as_view(), name="api_start_transport_out"),
        path("confirm_arrival", apis.ConfirmArrival.as_view(), name="api_confirm_arrival"),
        path("confirm_sign_for", apis.ConfirmSignFor.as_view(), name="api_confirm_sign_for"),
        path("department_payment/", include([
            path("modify_remark", apis.ModifyRemarkDepartmentPayment.as_view(),
                 name="api_modify_remark_department_payment"),
            path("drop", apis.DropDepartmentPayment.as_view(),
                 name="api_drop_department_payment"),
            path("review", apis.ConfirmReviewDepartmentPayment.as_view(),
                 name="api_review_department_payment"),
            path("pay", apis.ConfirmPayDepartmentPayment.as_view(),
                 name="api_pay_department_payment"),
            path("settle_accounts", apis.ConfirmSettleAccountsDepartmentPayment.as_view(),
                 name="api_settle_accounts_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("drop", apis.DropCargoPricePayment.as_view(),
                 name="api_drop_cargo_price_payment"),
            path("submit", apis.ConfirmSubmitCargoPricePayment.as_view(),
                 name="api_submit_cargo_price_payment"),
            path("review", apis.ConfirmReviewCargoPricePayment.as_view(),
                 name="api_review_cargo_price_payment"),
            path("reject", apis.ConfirmRejectCargoPricePayment.as_view(),
                 name="api_reject_cargo_price_payment"),
            path("pay", apis.ConfirmPayCargoPricePayment.as_view(),
                 name="api_pay_cargo_price_payment"),
        ])),
    ])),
]

wuliu/templates/wuliu/transport_out/_layout_edit_transport_out.html
{% extends "wuliu/_layout.html" %}
{% load wuliu_extras %}
{% block head_append_js %}
    <script src="{% url 'wuliu:edit_transport_out_js' %}"></script>
{% endblock %}
          {% block content %}
            <form class="form col-12 mb-2" id="form-edit_transport_out" method="post">
                <fieldset>
                  {% if not detail_view %}
                    {% csrf_token %}
                  {% endif %}
                    <legend class="row">基本信息</legend>
                  {% if form.id_ %}
                    <div class="row">
                        {% show_form_input_field form.id_ "" "col-6 col-md-3" %}
                        {% show_form_input_field form.id "" "" %}
                      {% if detail_view %}
                        {% show_form_input_field form.status "" "col-6 col-md-2" %}
                        {% show_form_input_field form.create_time %}
                        {% show_form_input_field form.start_time %}
                        {% show_form_input_field form.end_time %}
                      {% endif %}
                    </div>
                  {% endif %}
                    <div class="row">
                        {% show_form_input_field form.src_department "发车部门" "col-6 col-md-3" %}
                        {% show_form_input_field form.dst_department "到达部门" "col-6 col-md-3" %}
                    </div>
                    <legend class="row">车次信息</legend>
                    <div class="row">
                        {% show_form_input_field form.truck "选择车辆" "col-12 col-md-3" %}
                        {% show_form_input_field form.driver_name "" "col-6 col-md-3" %}
                        {% show_form_input_field form.driver_phone "" "col-6 col-md-3" %}
                    </div>
                    {# 此处不应该渲染该表单字段 #}
                    {# form.waybills #}
                </fieldset>
            </form>
            <div class="col-12 mb-2">
              {% block action_bar %}
                <a class="btn btn-outline-primary btn-sm" href="{% url 'wuliu:search_waybills_to_transport_out' %}">
                    <i class="ri-c ri-add-fill"><span>配载运单</span></i>
                </a>
                <button class="btn btn-outline-primary btn-sm" id="button_wb_remove">
                    <i class="ri-c ri-delete-bin-line"><span>删除</span></i>
                </button>
              {% endblock %}
            </div>
            <div class="col-12">
              {% block waybill_table %}
                {% show_waybill_table waybills_info_list "ready_transport_out" %}
              {% endblock %}
            </div>
            <div class="col-12">
              {% block action_buttons %}{% endblock %}
            </div>
          {% endblock %}

wuliu/templates/wuliu/transport_out/add_transport_out.html
{% extends "wuliu/transport_out/_layout_edit_transport_out.html" %}
{% block title %}创建车次计划{% endblock %}
{% block header_title %}创建车次计划{% endblock %}
{% block header_subtitle %}创建车次计划{% endblock %}
{% block head_append_js %}
    {{ block.super }}
    <script>
$(document).ready(function() {
  $("#button_wb_remove").click(function() {
    let checked_waybills = find_datatable_rows_clicked(ready_transport_out_table);
    if (checked_waybills.length === 0) {
      mdtoast_error("你没有选择任何运单。");
      return;
    }
    confirm_dialog(
      "移除运单", "你确定要从该车次中移除这些运单吗？", {
        okClick: function() {
          this.hide();
          let remove_list = checked_waybills.map(function(jq_obj) {
            return jq_obj.find("[data-wb_id]").attr("data-wb_id");
          });
          $.post(
            "{% url 'wuliu:api_remove_waybill_when_add_transport_out' %}",
            {
              "remove_list": remove_list.join(","),
            },
            function(data, status) {
              if (data.code === 200) {
                ready_transport_out_table.rows().nodes().each(function(row) {
                  if ($(row).find("input:checkbox").is(":checked")) {
                    ready_transport_out_table.row(row).remove();
                  }
                });
                ready_transport_out_table.draw();
                mdtoast_success("移除成功。");
              } else {
                mdtoast_error("移除失败。");
              }
            }
          );
        }
      }
    );
  });
});
    </script>
{% endblock %}
              {% block action_buttons %}
                <button class="btn btn-primary" id="transport_submit">创建车次</button>
              {% endblock %}

wuliu/templates/wuliu/transport_out/detail_transport_out.html
{% extends "wuliu/transport_out/_layout_edit_transport_out.html" %}
{% load wuliu_extras %}
{% block title %}车次详情{% endblock %}
{% block header_title %}车次详情{% endblock %}
              {% block action_bar %}{% endblock %}
              {% block waybill_table %}
                {% show_waybill_table waybills_info_list "ready_transport_out" False %}
              {% endblock %}

wuliu/templates/wuliu/transport_out/edit_transport_out.html
{% extends "wuliu/transport_out/_layout_edit_transport_out.html" %}
{% block title %}修改车次计划{% endblock %}
{% block header_title %}修改车次计划{% endblock %}
{% block head_append_js %}
    {{ block.super }}
    <script>
$(document).ready(function() {
  $("#button_wb_remove").click(function() {
    let checked_waybills = find_datatable_rows_clicked(ready_transport_out_table);
    if (checked_waybills.length === 0) {
      mdtoast_error("你没有选择任何运单。");
      return;
    }
    confirm_dialog(
      "移除运单", "你确定要从该车次中移除这些运单吗？", {
        okClick: function() {
          this.hide();
          let remove_list = checked_waybills.map(function(jq_obj) {
            return jq_obj.find("[data-wb_id]").attr("data-wb_id");
          });
          $.post(
            "{% url 'wuliu:api_remove_waybill_when_edit_transport_out' %}",
            {
              "remove_list": remove_list.join(","),
            },
            function(data, status) {
              if (data.code === 200) {
                ready_transport_out_table.rows().nodes().each(function(row) {
                  if ($(row).find("input:checkbox").is(":checked")) {
                    ready_transport_out_table.row(row).remove();
                  }
                });
                ready_transport_out_table.draw();
                mdtoast_success("移除成功。");
              } else {
                mdtoast_error("移除失败。");
              }
            }
          );
        }
      }
    );
  });
});
    </script>
{% endblock %}
              {% block action_buttons %}
                <button class="btn btn-primary" id="transport_submit">提交更改</button>
              {% endblock %}

wuliu/templates/wuliu/transport_out/manage_transport_out.html
{% extends "wuliu/_layout.html" %}
{% load wuliu_extras %}
{% block title %}发车出库{% endblock %}
{% block header_title %}发车出库{% endblock %}
{% block header_subtitle %}车次管理{% endblock %}
{% block head_append_js %}
    <script src="{% url 'wuliu:manage_transport_out_js' %}"></script>
{% endblock %}
          {% block content %}
            <form action="{% url 'wuliu:manage_transport_out' %}" id="form-search_transport_out" class="form col-12 mb-2" method="post">
                <fieldset>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-10">
                            <div class="row">
                                {% show_form_input_field form.transport_out_id "" "col-6 col-md" %}
                                {% show_form_input_field form.truck_number_plate "" "col-6 col-md" %}
                                {% show_form_input_field form.driver_name "" "col-6 col-md" %}
                                {% show_form_input_field form.status "" "col-6 col-md" %}
                            </div>
                            <div class="row">
                                {% show_form_input_field form.create_date_start "" "col-6 col-md" %}
                                {% show_form_input_field form.create_date_end "" "col-6 col-md" %}
                                {% show_form_input_field form.src_department "" "col-6 col-md" %}
                                {% show_form_input_field form.dst_department "" "col-6 col-md" %}
                            </div>
                        </div>
                        <div class="col-md child-flex child-flex-xc child-flex-yc pt-2">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-search"> 查询</i>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
            <div class="col-12 mb-2">
              {% if "manage_transport_out__add_edit_delete_start"|is_logged_user_has_perm:request %}
                <a class="btn btn-outline-primary btn-sm" href="{% url 'wuliu:add_transport_out' %}">
                    <i class="ri-c ri-add-fill"><span>新增</span></i>
                </a>
                <button class="btn btn-outline-primary btn-sm" id="button_to_edit">
                    <i class="ri-c ri-file-edit-line"><span>修改</span></i>
                </button>
                <button class="btn btn-outline-primary btn-sm" id="button_to_drop">
                    <i class="ri-c ri-delete-bin-line"><span>删除车次</span></i>
                </button>
                <button class="btn btn-outline-primary btn-sm" id="button_to_start">
                    <i class="ri-c ri-truck-line"><span>确认发车</span></i>
                </button>
              {% endif %}
            </div>
            <div class="col-12">
                {% show_transport_out_table transport_out_list "to_search_result" %}
            </div>
          {% endblock %}

wuliu/templates/wuliu/transport_out/search_waybills_to_transport_out.html
{% extends "wuliu/waybill/_layout_search_waybill.html" %}
{% block title %}选择运单{% endblock %}
{% block header_title %}选择运单{% endblock %}
{% block header_subtitle %}请查询并选择你需要配载的运单{% endblock %}
              {% block search_form_action %}{% url 'wuliu:search_waybills_to_transport_out' %}{% endblock %}
              {% block action_bar %}
                <form id="form-add_waybills_to_transport_out" action="{% url 'wuliu:add_waybills_to_transport_out' %}" method="post" hidden>
                    {% csrf_token %}
                    <input type="text" name="wb_add_list">
                </form>
                <button class="btn btn-outline-primary btn-sm" id="wb_add_submit">
                    <i class="ri-c ri-add-fill"><span>添加</span></i>
                </button>
                <script>
$(document).ready(function() {
  $("#wb_add_submit").click(function() {
    let checked_waybills = find_datatable_rows_clicked(wb_search_result_table);
    if (checked_waybills.length === 0) {
      mdtoast_error("请至少选择一个运单。");
      return;
    }
    for (let jq_obj of checked_waybills.toArray()) {
    {% if logged_user_type == USER_TYPES.GoodsYard %}
      if (jq_obj.find("[data-status_id]").attr("data-status_id") != "{{ WB_STATUSES.GoodsYardArrived }}") {
        mdtoast_error('只能选择"货场入库"状态的运单。');
        return;
      }
    {% else %}
      if (jq_obj.find("[data-status_id]").attr("data-status_id") >= "{{ WB_STATUSES.Loaded }}") {
        mdtoast_error("只能选择尚未配载/发车的运单。");
        return;
      }
    {% endif %}
    }
    let waybills_ready_to_transport_out = checked_waybills.map(function(jq_obj) {
      return jq_obj.find("[data-wb_id]").attr("data-wb_id");
    });
    $('#form-add_waybills_to_transport_out [name="wb_add_list"]').val(waybills_ready_to_transport_out.join(","));
    $('#form-add_waybills_to_transport_out').submit();
  });
});
                </script>
              {% endblock %}