PPWuLiu/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', RedirectView.as_view(url='tms/login')),
    path('tms/', include('wuliu.urls')),
    path('utils/', include('utils.urls')),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

utils/urls.py
from django.urls import path

from . import views

app_name = "utils"
urlpatterns = [
    path("export_excel", views.export_excel, name="export_excel"),
]

wuliu/urls.py
from django.urls import path, include


# Unused
from wuliu import views, apis


def easy_path(view_func):
    """ 只需给定视图函数, route和name都设置为视图函数的名字 """
    return path(view_func.__name__, view_func, name=view_func.__name__)

app_name = "wuliu"
# urlpatterns = []

urlpatterns = [
    # 登录
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("change_password", views.change_password, name="change_password"),
    path("", views.welcome, name="welcome"),
    path("welcome_action.js", views.welcome_js, name="welcome_js"),
    # 系统设置
    path("settings/", include([
        path("manage_users", views.manage_users, name="manage_users"),
        path("add_user", views.add_user, name="add_user"),
        path("manage_user_permission", views.manage_user_permission, name="manage_user_permission"),
        path("batch_edit_user_permission", views.batch_edit_user_permission, name="batch_edit_user_permission"),
    ])),
    # 运单管理
    path("waybill/", include([
        path("add", views.add_waybill, name="add_waybill"),
        path("edit", views.edit_waybill, name="edit_waybill"),
        path("edit.js", views.edit_waybill_js, name="edit_waybill_js"),
        path("manage", views.ManageWaybill.as_view(), name="manage_waybill"),
        path("manage.js", views.manage_waybill_js, name="manage_waybill_js"),
        path("detail/<int:waybill_id>", views.detail_waybill, name="detail_waybill"),
        path("quick_search", views.quick_search_waybill, name="quick_search_waybill"),
        path("confirm_return", views.confirm_return_waybill, name="confirm_return_waybill"),
    ])),
    # 发车管理
    path("transport_out/", include([
        path("add", views.add_transport_out, name="add_transport_out"),
        path("edit", views.edit_transport_out, name="edit_transport_out"),
        path("edit.js", views.edit_transport_out_js, name="edit_transport_out_js"),
        path("manage", views.manage_transport_out, name="manage_transport_out"),
        path("manage.js", views.manage_transport_out_js, name="manage_transport_out_js"),
        path("detail", views.detail_transport_out, name="detail_transport_out"),
        path("search_waybills", views.SearchWaybillsToTransportOut.as_view(), name="search_waybills_to_transport_out"),
        path("add_waybills", views.add_waybills_to_transport_out, name="add_waybills_to_transport_out"),
    ])),
    # 到货管理
    path("arrival/", include([
        path("manage", views.manage_arrival, name="manage_arrival"),
        path("confirm", views.confirm_arrival, name="confirm_arrival"),
    ])),
    # 客户签收
    path("sign_for/", include([
        path("manage", views.ManageSignFor.as_view(), name="manage_sign_for"),
        path("confirm", views.confirm_sign_for, name="confirm_sign_for"),
        path("confirm.js", views.confirm_sign_for_js, name="confirm_sign_for_js"),
    ])),
    # 财务管理
    path("finance/", include([
        path("department_payment/", include([
            path("add", views.add_department_payment, name="add_department_payment"),
            path("manage", views.manage_department_payment, name="manage_department_payment"),
            path("manage.js", views.manage_department_payment_js, name="manage_department_payment_js"),
            path("detail/<int:dp_id>", views.detail_department_payment, name="detail_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("add", views.add_cargo_price_payment, name="add_cargo_price_payment"),
            path("edit", views.edit_cargo_price_payment, name="edit_cargo_price_payment"),
            path("edit.js", views.edit_cargo_price_payment_js, name="edit_cargo_price_payment_js"),
            path("detail/<int:cpp_id>", views.detail_cargo_price_payment, name="detail_cargo_price_payment"),
            path("manage", views.manage_cargo_price_payment, name="manage_cargo_price_payment"),
            path("manage.js", views.manage_cargo_price_payment_js, name="manage_cargo_price_payment_js"),
        ])),
        path("customer_score_log/", include([
            path("manage", views.manage_customer_score, name="manage_customer_score"),
            path("add", views.add_customer_score_log, name="add_customer_score_log"),
        ])),
    ])),
    # 业务报表
    path("report_table/", include([
        path("src_waybill", views.ReportTableSrcWaybill.as_view(), name="report_table_src_waybill"),
        path("stock_waybill", views.ReportTableStockWaybill.as_view(), name="report_table_stock_waybill"),
        path("dst_waybill", views.ReportTableDstWaybill.as_view(), name="report_table_dst_waybill"),
        path("dst_stock_waybill", views.ReportTableDstStockWaybill.as_view(), name="report_table_dst_stock_waybill"),
        path("sign_for_waybill", views.ReportTableSignForWaybill.as_view(), name="report_table_sign_for_waybill"),
    ])),
    # apis
    path("api/", include([
        path("gen_standard_fee", apis.gen_standard_fee, name="api_gen_standard_fee"),
        path("check_old_password", apis.check_old_password, name="api_check_old_password"),
        # 用以获取模型对象属性的api
        path("get/", include([
            path("customer_info", apis.get_customer_info, name="api_get_customer_info"),
            path("department_info", apis.get_department_info, name="api_get_department_info"),
            path("waybills_info", apis.get_waybills_info, name="api_get_waybills_info"),
            path("truck_info", apis.get_truck_info, name="api_get_truck_info"),
            path("user_info", apis.get_user_info, name="api_get_user_info"),
            path("user_permission", apis.get_user_permission, name="api_get_user_permission"),
        ])),
        # 用以操作模型和会话的api
        path("remove_waybill_when_add_transport_out", apis.remove_waybill_when_add_transport_out,
             name="api_remove_waybill_when_add_transport_out"),
        path("remove_waybill_when_edit_transport_out", apis.remove_waybill_when_edit_transport_out,
             name="api_remove_waybill_when_edit_transport_out"),
        path("add_waybill_when_confirm_sign_for", apis.add_waybill_when_confirm_sign_for,
             name="api_add_waybill_when_confirm_sign_for"),
        path("add_waybill_when_edit_cargo_price_payment", apis.add_waybill_when_edit_cargo_price_payment,
             name="api_add_waybill_when_edit_cargo_price_payment"),
        path("drop_waybill", apis.DropWaybill.as_view(), name="api_drop_waybill"),
        path("drop_transport_out", apis.DropTransportOut.as_view(), name="api_drop_transport_out"),
        path("start_transport_out", apis.StartTransportOut.as_view(), name="api_start_transport_out"),
        path("confirm_arrival", apis.ConfirmArrival.as_view(), name="api_confirm_arrival"),
        path("confirm_sign_for", apis.ConfirmSignFor.as_view(), name="api_confirm_sign_for"),
        path("department_payment/", include([
            path("modify_remark", apis.ModifyRemarkDepartmentPayment.as_view(),
                 name="api_modify_remark_department_payment"),
            path("drop", apis.DropDepartmentPayment.as_view(),
                 name="api_drop_department_payment"),
            path("review", apis.ConfirmReviewDepartmentPayment.as_view(),
                 name="api_review_department_payment"),
            path("pay", apis.ConfirmPayDepartmentPayment.as_view(),
                 name="api_pay_department_payment"),
            path("settle_accounts", apis.ConfirmSettleAccountsDepartmentPayment.as_view(),
                 name="api_settle_accounts_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("drop", apis.DropCargoPricePayment.as_view(),
                 name="api_drop_cargo_price_payment"),
            path("submit", apis.ConfirmSubmitCargoPricePayment.as_view(),
                 name="api_submit_cargo_price_payment"),
            path("review", apis.ConfirmReviewCargoPricePayment.as_view(),
                 name="api_review_cargo_price_payment"),
            path("reject", apis.ConfirmRejectCargoPricePayment.as_view(),
                 name="api_reject_cargo_price_payment"),
            path("pay", apis.ConfirmPayCargoPricePayment.as_view(),
                 name="api_pay_cargo_price_payment"),
        ])),
    ])),
]

wuliu/templates/wuliu/finance/cargo_price_payment/_layout_edit_cargo_price_payment.html
{% extends "wuliu/_layout.html" %}
{% load wuliu_extras %}
{% block head_append_js %}
  <script src="{% url 'wuliu:edit_cargo_price_payment_js' %}"></script>
{% endblock %}
          {% block content %}
            <form action="{% block form_action %}{% endblock %}" id="form-payee_info" class="form col-12 mb-2" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend class="row">收款人信息</legend>
                  {% if form.id_ %}
                    {{ form.id }}
                    <div class="row">
                        {% show_form_input_field form.id_ "" "col-8 col-md-3" %}
                      {% if form.status %}
                        {% show_form_input_field form.status "" "col-4 col-md-3" %}
                      {% endif %}
                      {% if form.create_time %}
                        {% show_form_input_field form.create_time "" "col-6 col-md-3" %}
                      {% endif %}
                      {% if form.settle_accounts_time %}
                        {% show_form_input_field form.settle_accounts_time "" "col-6 col-md-3" %}
                      {% endif %}
                    </div>
                  {% endif %}
                    <div class="row">
                      {% if form.customer %}
                        {% show_form_input_field form.customer "" "col-12 col-md-3" %}
                      {% endif %}
                        {% show_form_input_field form.payee_name "" "col-5 col-md-3" %}
                        {% show_form_input_field form.payee_phone "" "col-7 col-md-3" %}
                    </div>
                    <div class="row">
                        {% show_form_input_field form.payee_bank_name "" "col-5 col-md-3" %}
                        {% show_form_input_field form.payee_bank_number "" "col-7 col-md" %}
                        {% show_form_input_field form.payee_credential_num "" "col-12 col-md" %}
                    </div>
                    <div class="row">
                        {% show_form_input_field form.remark "" "col-12 col-md-6" %}
                      {% if detail_view %}
                        {% show_form_input_field form.reject_reason "" "col-12 col-md-6" %}
                      {% endif %}
                    </div>
                    <input name="waybill_ids" hidden>
                </fieldset>
            </form>
            <form id="form-add_cargo_price_payment_waybill" class="form col-12 mb-2">
                <fieldset>
                    <legend class="row">费用列表</legend>
                  {% if not detail_view %}
                    <div class="row">
                        <div class="input-group col-md-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text text-sm">添加运单</span>
                            </div>
                            <input type="text" class="form-control" name="add_waybill_id" aria-label="Default" data-allow_enter_submit>
                        </div>
                    </div>
                  {% endif %}
                </fieldset>
            </form>
            <div class="col-12 mb-2">
              {% block action_bar %}
              {% endblock %}
            </div>
            <div class="col-12">
              {% show_waybill_table waybill_list "cpp_waybill" %}
            </div>
            <div class="col-12">
              {% block action_buttons %}
              {% endblock %}
            </div>
          {% endblock %}

wuliu/templates/wuliu/finance/cargo_price_payment/add_cargo_price_payment.html
{% extends "wuliu/finance/cargo_price_payment/_layout_edit_cargo_price_payment.html" %}
{% block title %}新建代收款转账单{% endblock %}
{% block header_title %}新建代收款转账单{% endblock %}
{% block form_action %}{% url 'wuliu:add_cargo_price_payment' %}{% endblock %}
              {% block action_bar %}
                <button class="btn btn-outline-primary btn-sm" id="button_wb_remove">
                    <i class="ri-c ri-delete-bin-line"><span>删除</span></i>
                </button>
              {% endblock %}
              {% block action_buttons %}
                <button class="btn btn-primary" id="button_cargo_price_payment_submit">提交</button>
              {% endblock %}

wuliu/templates/wuliu/finance/cargo_price_payment/detail_cargo_price_payment.html
{% extends "wuliu/finance/cargo_price_payment/_layout_edit_cargo_price_payment.html" %}
{% block title %}代收款转账单详情{% endblock %}
{% block header_title %}代收款转账单详情{% endblock %}
{% block head_append_js %}{% endblock %}
{% block form_action %}{% endblock %}
              {% block action_bar %}
                <blockquote>
                    <h1>应转账金额</h1>
                    <p>
                        代收货款总计：<code>{{ cpp_dic.total_cargo_price }}</code>元；
                        扣付运费总计：<code>{{ cpp_dic.total_deduction_fee }}</code>元；
                        扣付手续费总计：<code>{{ cpp_dic.total_cargo_handling_fee }}</code>元；
                        合计：<code>{{ cpp_dic.final_fee }}</code>元。
                    </p>
                </blockquote>
              {% endblock %}

wuliu/templates/wuliu/finance/cargo_price_payment/edit_cargo_price_payment.html
{% extends "wuliu/finance/cargo_price_payment/add_cargo_price_payment.html" %}
{% block title %}修改代收款转账单{% endblock %}
{% block header_title %}修改代收款转账单{% endblock %}
{% block form_action %}{% url 'wuliu:edit_cargo_price_payment' %}{% endblock %}

wuliu/templates/wuliu/finance/cargo_price_payment/manage_cargo_price_payment.html
{% extends "wuliu/_layout.html" %}
{% load wuliu_extras %}
{% block title %}代收款转账单{% endblock %}
{% block header_title %}代收款转账单{% endblock %}
{% block header_subtitle %}创建 -&gt; 提交 -&gt; 财务部审核 -&gt; 财务部支付并结算{% endblock %}
{% block head_append_js %}
    <script src="{% url 'wuliu:manage_cargo_price_payment_js' %}"></script>
{% endblock %}
          {% block content %}
            <form action="{% url 'wuliu:manage_cargo_price_payment' %}" id="form-search_cargo_price_payment" class="form col-12 mb-2" method="post">
                <fieldset>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-10">
                            <div class="row">
                                {% show_form_input_field form.create_user "" "col-6 col-md-3" %}
                                {% show_form_input_field form.create_department "" "col-6 col-md-3" %}
                                {% show_form_input_field form.payee_name "" "col-6 col-md-3" %}
                                {% show_form_input_field form.status "" "col-6 col-md-3" %}
                                {% show_form_input_field form.create_date_start "" "col-6 col-md-3" %}
                                {% show_form_input_field form.create_date_end "" "col-6 col-md-3" %}
                                {% show_form_input_field form.settle_accounts_date_start "" "col-6 col-md-3" %}
                                {% show_form_input_field form.settle_accounts_date_end "" "col-6 col-md-3" %}
                            </div>
                        </div>
                        <div class="col-md child-flex child-flex-xc child-flex-yc pt-2">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-search"> 查询</i>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
            <div class="col-12 mb-2">
              {% if "manage_cargo_price_payment__add_edit_delete_submit"|is_logged_user_has_perm:request %}
                <a href="{% url 'wuliu:add_cargo_price_payment' %}" class="btn btn-outline-primary btn-sm">
                    <i class="ri-c ri-add-fill"><span>新增</span></i>
                </a>
                <button class="btn btn-outline-primary btn-sm" id="button_cpp_edit">
                    <i class="ri-c ri-file-edit-line"><span>修改</span></i>
                </button>
                <button class="btn btn-outline-primary btn-sm" id="button_cpp_delete">
                    <i class="ri-c ri-delete-bin-line"><span>删除</span></i>
                </button>
                <button class="btn btn-outline-primary btn-sm" id="button_cpp_confirm_submit">
                    <i class="ri-c ri-share-forward-line"><span>确认提交</span></i>
                </button>
              {% endif %}
              {% if "manage_cargo_price_payment__review_reject"|is_logged_user_has_perm:request %}
                <button class="btn btn-outline-primary btn-sm" id="button_cpp_confirm_review">
                    <i class="ri-c ri-eye-line"><span>确认审核</span></i>
                </button>
                <button class="btn btn-outline-primary btn-sm" id="button_cpp_confirm_reject">
                    <i class="ri-c ri-emotion-unhappy-line"><span>驳回</span></i>
                </button>
              {% endif %}
              {% if "manage_cargo_price_payment__pay"|is_logged_user_has_perm:request %}
                <button class="btn btn-outline-primary btn-sm" id="button_cpp_confirm_pay">
                    <i class="ri-c ri-money-cny-circle-line"><span>确认支付</span></i>
                </button>
              {% endif %}
            </div>
            <div class="col-12">
                {% show_cargo_price_payment_table cargo_price_payment_list "cargo_price_payment" %}
            </div>
          {% endblock %}