PPWuLiu/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic.base import RedirectView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', RedirectView.as_view(url='tms/login')),
    path('tms/', include('wuliu.urls')),
    path('utils/', include('utils.urls')),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

utils/urls.py
from django.urls import path

from . import views

app_name = "utils"
urlpatterns = [
    path("export_excel", views.export_excel, name="export_excel"),
]

wuliu/urls.py
from django.urls import path, include


# Unused
from wuliu import views, apis


def easy_path(view_func):
    """ 只需给定视图函数, route和name都设置为视图函数的名字 """
    return path(view_func.__name__, view_func, name=view_func.__name__)

app_name = "wuliu"
# urlpatterns = []

urlpatterns = [
    # 登录
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("change_password", views.change_password, name="change_password"),
    path("", views.welcome, name="welcome"),
    path("welcome_action.js", views.welcome_js, name="welcome_js"),
    # 系统设置
    path("settings/", include([
        path("manage_users", views.manage_users, name="manage_users"),
        path("add_user", views.add_user, name="add_user"),
        path("manage_user_permission", views.manage_user_permission, name="manage_user_permission"),
        path("batch_edit_user_permission", views.batch_edit_user_permission, name="batch_edit_user_permission"),
    ])),
    # 运单管理
    path("waybill/", include([
        path("add", views.add_waybill, name="add_waybill"),
        path("edit", views.edit_waybill, name="edit_waybill"),
        path("edit.js", views.edit_waybill_js, name="edit_waybill_js"),
        path("manage", views.ManageWaybill.as_view(), name="manage_waybill"),
        path("manage.js", views.manage_waybill_js, name="manage_waybill_js"),
        path("detail/<int:waybill_id>", views.detail_waybill, name="detail_waybill"),
        path("quick_search", views.quick_search_waybill, name="quick_search_waybill"),
        path("confirm_return", views.confirm_return_waybill, name="confirm_return_waybill"),
    ])),
    # 发车管理
    path("transport_out/", include([
        path("add", views.add_transport_out, name="add_transport_out"),
        path("edit", views.edit_transport_out, name="edit_transport_out"),
        path("edit.js", views.edit_transport_out_js, name="edit_transport_out_js"),
        path("manage", views.manage_transport_out, name="manage_transport_out"),
        path("manage.js", views.manage_transport_out_js, name="manage_transport_out_js"),
        path("detail", views.detail_transport_out, name="detail_transport_out"),
        path("search_waybills", views.SearchWaybillsToTransportOut.as_view(), name="search_waybills_to_transport_out"),
        path("add_waybills", views.add_waybills_to_transport_out, name="add_waybills_to_transport_out"),
    ])),
    # 到货管理
    path("arrival/", include([
        path("manage", views.manage_arrival, name="manage_arrival"),
        path("confirm", views.confirm_arrival, name="confirm_arrival"),
    ])),
    # 客户签收
    path("sign_for/", include([
        path("manage", views.ManageSignFor.as_view(), name="manage_sign_for"),
        path("confirm", views.confirm_sign_for, name="confirm_sign_for"),
        path("confirm.js", views.confirm_sign_for_js, name="confirm_sign_for_js"),
    ])),
    # 财务管理
    path("finance/", include([
        path("department_payment/", include([
            path("add", views.add_department_payment, name="add_department_payment"),
            path("manage", views.manage_department_payment, name="manage_department_payment"),
            path("manage.js", views.manage_department_payment_js, name="manage_department_payment_js"),
            path("detail/<int:dp_id>", views.detail_department_payment, name="detail_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("add", views.add_cargo_price_payment, name="add_cargo_price_payment"),
            path("edit", views.edit_cargo_price_payment, name="edit_cargo_price_payment"),
            path("edit.js", views.edit_cargo_price_payment_js, name="edit_cargo_price_payment_js"),
            path("detail/<int:cpp_id>", views.detail_cargo_price_payment, name="detail_cargo_price_payment"),
            path("manage", views.manage_cargo_price_payment, name="manage_cargo_price_payment"),
            path("manage.js", views.manage_cargo_price_payment_js, name="manage_cargo_price_payment_js"),
        ])),
        path("customer_score_log/", include([
            path("manage", views.manage_customer_score, name="manage_customer_score"),
            path("add", views.add_customer_score_log, name="add_customer_score_log"),
        ])),
    ])),
    # 业务报表
    path("report_table/", include([
        path("src_waybill", views.ReportTableSrcWaybill.as_view(), name="report_table_src_waybill"),
        path("stock_waybill", views.ReportTableStockWaybill.as_view(), name="report_table_stock_waybill"),
        path("dst_waybill", views.ReportTableDstWaybill.as_view(), name="report_table_dst_waybill"),
        path("dst_stock_waybill", views.ReportTableDstStockWaybill.as_view(), name="report_table_dst_stock_waybill"),
        path("sign_for_waybill", views.ReportTableSignForWaybill.as_view(), name="report_table_sign_for_waybill"),
    ])),
    # apis
    path("api/", include([
        path("gen_standard_fee", apis.gen_standard_fee, name="api_gen_standard_fee"),
        path("check_old_password", apis.check_old_password, name="api_check_old_password"),
        # 用以获取模型对象属性的api
        path("get/", include([
            path("customer_info", apis.get_customer_info, name="api_get_customer_info"),
            path("department_info", apis.get_department_info, name="api_get_department_info"),
            path("waybills_info", apis.get_waybills_info, name="api_get_waybills_info"),
            path("truck_info", apis.get_truck_info, name="api_get_truck_info"),
            path("user_info", apis.get_user_info, name="api_get_user_info"),
            path("user_permission", apis.get_user_permission, name="api_get_user_permission"),
        ])),
        # 用以操作模型和会话的api
        path("remove_waybill_when_add_transport_out", apis.remove_waybill_when_add_transport_out,
             name="api_remove_waybill_when_add_transport_out"),
        path("remove_waybill_when_edit_transport_out", apis.remove_waybill_when_edit_transport_out,
             name="api_remove_waybill_when_edit_transport_out"),
        path("add_waybill_when_confirm_sign_for", apis.add_waybill_when_confirm_sign_for,
             name="api_add_waybill_when_confirm_sign_for"),
        path("add_waybill_when_edit_cargo_price_payment", apis.add_waybill_when_edit_cargo_price_payment,
             name="api_add_waybill_when_edit_cargo_price_payment"),
        path("drop_waybill", apis.DropWaybill.as_view(), name="api_drop_waybill"),
        path("drop_transport_out", apis.DropTransportOut.as_view(), name="api_drop_transport_out"),
        path("start_transport_out", apis.StartTransportOut.as_view(), name="api_start_transport_out"),
        path("confirm_arrival", apis.ConfirmArrival.as_view(), name="api_confirm_arrival"),
        path("confirm_sign_for", apis.ConfirmSignFor.as_view(), name="api_confirm_sign_for"),
        path("department_payment/", include([
            path("modify_remark", apis.ModifyRemarkDepartmentPayment.as_view(),
                 name="api_modify_remark_department_payment"),
            path("drop", apis.DropDepartmentPayment.as_view(),
                 name="api_drop_department_payment"),
            path("review", apis.ConfirmReviewDepartmentPayment.as_view(),
                 name="api_review_department_payment"),
            path("pay", apis.ConfirmPayDepartmentPayment.as_view(),
                 name="api_pay_department_payment"),
            path("settle_accounts", apis.ConfirmSettleAccountsDepartmentPayment.as_view(),
                 name="api_settle_accounts_department_payment"),
        ])),
        path("cargo_price_payment/", include([
            path("drop", apis.DropCargoPricePayment.as_view(),
                 name="api_drop_cargo_price_payment"),
            path("submit", apis.ConfirmSubmitCargoPricePayment.as_view(),
                 name="api_submit_cargo_price_payment"),
            path("review", apis.ConfirmReviewCargoPricePayment.as_view(),
                 name="api_review_cargo_price_payment"),
            path("reject", apis.ConfirmRejectCargoPricePayment.as_view(),
                 name="api_reject_cargo_price_payment"),
            path("pay", apis.ConfirmPayCargoPricePayment.as_view(),
                 name="api_pay_cargo_price_payment"),
        ])),
    ])),
]

wuliu/templates/wuliu/_layout.html
<!DOCTYPE html>
{% load static %}
{% load wuliu_extras %}
<html lang="zh">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="theme-color" content="#3d4f5d">

  <title>{% block title %}{% endblock %} | {% get_company_name %}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/select2/css/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/datatables-fixedcolumns/css/fixedColumns.bootstrap4.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'AdminLTE-3.0.5/plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'AdminLTE-3.0.5/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- overlayScrollbars -->
  <script src="{% static 'AdminLTE-3.0.5/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
  <!-- Select2 -->
  <script src="{% static 'AdminLTE-3.0.5/plugins/select2/js/select2.full.min.js' %}"></script>
  <!-- DataTables -->
  <script src="{% static 'AdminLTE-3.0.5/plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/plugins/datatables-fixedcolumns/js/dataTables.fixedColumns.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/plugins/datatables-fixedcolumns/js/fixedColumns.bootstrap4.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'AdminLTE-3.0.5/dist/js/adminlte.min.js' %}"></script>

  <!-- Custom -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/remixicon/remixicon.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/duDatepicker.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/mdtimepicker.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/duDialog.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/mdtoast.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/multiple-select/multiple-select.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/multiple-select/theme/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  {% block head_append_css %}
  {% endblock %}

  <script src="{% static 'js/duDatepicker.min.js' %}"></script>
  <script src="{% static 'js/mdtimepicker.min.js' %}"></script>
  <script src="{% static 'js/duDialog.min.js' %}"></script>
  <script src="{% static 'js/mdtoast.min.js' %}"></script>
  <script src="{% static 'js/multiple-select.min.js' %}"></script>
  <script src="{% static 'js/js.cookie-3.0.0.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  {% block head_append_js %}
  {% endblock %}

</head>

{# layout-fixed: 固定sidebar, 当sidebar内容过长时显示自定义滚动条(依赖: overlayScrollbars), 否则则使整个页面变长 #}
{# layout-navbar-fixed: 固定navbar, navbar始终在页面顶部 #}
{# sidebar-collapse: 收起sidebar, 通过点击'[data-widget="pushmenu"]'来切换 #}
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed {% if request.COOKIES.ui_enable_sidebar_collapse == 'true' %}sidebar-collapse{% endif %}">

<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'wuliu:welcome' %}" class="nav-link">首页</a>
      </li>
    </ul>

    <!-- Search FORM -->
    <form action="{% url 'wuliu:quick_search_waybill' %}" class="form-inline ml-3" method="post">
      {% csrf_token %}
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="text" name="search_string" placeholder="快速查单(运单号/姓名/电话)" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

  {% comment "Unused now" %}
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 条未读消息</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 条新消息
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 个好友请求
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 个问题报告
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">查看所有未读消息</a>
        </div>
      </li>
    </ul>
  {% endcomment %}
  </nav>

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'wuliu:welcome' %}" class="brand-link elevation-4">
      <img src="{% static 'AdminLTE-3.0.5/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">{% get_company_name %}有限公司</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <nav class="mt-2" style="border-bottom: 1px solid #4f5962;">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link" style="padding-left: 14px;">
              <img src="{% static 'AdminLTE-3.0.5/dist/img/user2-160x160.jpg' %}" class="nav-user-icon img-circle elevation-2" alt="User Image">
              <p>{{ request.session.user.name }} ({{ request.session.user.department_name }})</p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'wuliu:change_password' %}" class="nav-link ">
                  <i class="fas fa-lock nav-icon"></i>
                  <p>修改密码</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'wuliu:logout' %}" class="nav-link ">
                  <i class="fas fa-sign-out-alt nav-icon"></i>
                  <p>退出登录</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
            {% show_sidebar_menu_items %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper text-sm">
    <!-- Content Header (Page header) -->
    <div class="content-header ml-1">
      <div class="container-fluid">
        <div class="row mb-2">
          <h1 class="text-dark">{% block header_title %}{% endblock %}</h1>
        </div>
        <div class="row mb-2">
          <span class="text-muted">{% block header_subtitle %}{% endblock %}</span>
        </div>
      </div>
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
    {% for message in messages %}
      {% show_message message %}
    {% endfor %}
      <div class="container-fluid mb-4">
        <div class="card p-3 row">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    <!-- /.content -->
  </div>

  <!-- Main Footer -->
  <footer class="main-footer text-sm">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Copyright &copy; 2021. All rights reserved.
    </div>
    <!-- Default to the left -->
    <strong>Powered By
      <a href="https://adminlte.io" target="_blank">AdminLTE.io</a>
      ,
      <a href="https://www.djangoproject.com/" target="_blank">Django</a>
      .
    </strong>
  </footer>
</div>

</body>

{% comment "Disable WebSocket for now" %}
<script>
const messageSocket = new WebSocket('ws://' + window.location.host + '/ws/message/');

// 建立连接时: onopen
messageSocket.onopen = function(e) {
  console.log("Websocket has been successfully connected.");
};

// 收到消息时: onmessage
messageSocket.onmessage = function(e) {
  let json_data = JSON.parse(e.data);
  mdtoast_success("来自服务器的消息：" + json_data.message);
};

// 断开链接时: onclose
messageSocket.onclose = function(e) {
  console.error("Websocket closed unexpectedly.");
};

// 主动断开链接: close
// 发送消息: send
// messageSocket.send(JSON.stringify({
  // 'message': "测试消息"
// }));
</script>
{% endcomment %}

</html>

wuliu/templates/wuliu/change_password.html
{% extends "wuliu/_layout.html" %}
{% load wuliu_extras %}
{% block title %}修改密码{% endblock %}
{% block header_title %}修改密码{% endblock %}
          {% block content %}
            <form action="{% url 'wuliu:change_password' %}" id="form-change_password" class="form col-12 mb-2" method="post">
                <fieldset>
                    {% csrf_token %}
                    <div class="row">
                        {% show_form_input_field form.old_password "" "col-12 col-md-7" %}
                        <div class="col-12 col-md-5 align-self-end text-md">
                            <span id="old_password_note"></span>
                        </div>
                        {% show_form_input_field form.new_password "" "col-12 col-md-7" %}
                        {% show_form_input_field form.new_password_again "" "col-12 col-md-7" %}
                        <div class="col-12 col-md-5 align-self-end text-md">
                            <span id="new_password_again_note"></span>
                        </div>
                        <div class="col-12 mt-2">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-search"> 确定</i>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
            <script>
$(document).ready(function() {
  let old_password_flag = false;
  let new_password_flag = false;
  $('#form-change_password [name="old_password"]').change(function() {
    $.post(
      "{% url 'wuliu:api_check_old_password' %}",
      {"old_password": $(this).val()},
      function(data, status) {
        if (data.code === 200) {
          if (data.data.message === "success") {
            $("#old_password_note").html('<i class="ri-checkbox-circle-fill"></i>').attr("class", "text-success");
            old_password_flag = true;
          } else {
            $("#old_password_note").html('<i class="ri-close-circle-fill"></i> 旧密码错误！').attr("class", "text-danger");
            old_password_flag = false;
          }
        } else {
          $("#old_password_note").html('');
          old_password_flag = false;
          mdtoast_error(data.data.message);
        }
      }
    );
  });
  $('#form-change_password [name="new_password_again"]').change(function() {
    let new_password = $('#form-change_password [name="new_password"]').val().trim();
    let new_password_again = $(this).val().trim();
    if (new_password && new_password_again) {
      if (new_password === new_password_again) {
        $("#new_password_again_note").html('<i class="ri-checkbox-circle-fill"></i>').attr("class", "text-success");
        new_password_flag = true;
      } else {
        $("#new_password_again_note").html('<i class="ri-close-circle-fill"></i> 两次输入的新密码不一致！').attr("class", "text-danger");
        new_password_flag = false;
      }
    }
  });
  $("#form-change_password").submit(function(e) {
    if (old_password_flag && new_password_flag) return;
    e.preventDefault();
  });
});
            </script>
          {% endblock %}

wuliu/templates/wuliu/login.html
<!DOCTYPE html>
{% load static %}
{% load wuliu_extras %}
<html lang="zh">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="theme-color" content="#3d4f5d">

  <title>登录 | {% get_company_name %}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- Custom -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/mdtoast.css' %}">
  <script src="{% static 'js/mdtoast.min.js' %}"></script>

  <style>
    .background-img {
      background: url("{% static 'img/background.jpg' %}") no-repeat;
      background-size: cover;
    }
    .login-box-blur {
      background: rgba(255, 255, 255, 0.2);
      box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
      backdrop-filter: blur(8.5px);
      -webkit-backdrop-filter: blur(8.5px);
      border-radius: 10px;
      padding: 16px;
    }
    .input-blur {
      background-color: rgba(255, 255, 255, 0.3);
      border: none;
    }
    .input-group input::-webkit-input-placeholder {
      color: #555555;
    }
    .input-group input:-moz-placeholder {
      color: #555555;
    }
    .input-group input:-ms-input-placeholder {
      color: #555555;
    }
  </style>
</head>
<body class="hold-transition login-page background-img">
  <div class="login-box login-box-blur">
    <div class="login-logo text-white">{% get_company_name %}运输管理系统</div>
    <p class="login-box-msg text-white">请登录</p>
    <form class="mb-2" action="{% url 'wuliu:login' %}" method="post">
      {% csrf_token %}
      <div class="input-group mb-3">
        <input type="text" class="form-control input-blur" name="username" placeholder="用户名">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-user"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="password" class="form-control input-blur" name="password" placeholder="密码">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-lock"></span>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col"></div>
        <div class="col-4">
          <button type="submit" class="btn btn-primary btn-block">登录</button>
        </div>
      </div>
    </form>
  {% if messages %}
    <script>
      {% for message in messages %}
        mdtoast("{{ message }}", {type: mdtoast.ERROR});
      {% endfor %}
    </script>
  {% endif %}
  </div>
</body>
</html>